name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nagerat/aspnetcoretest:$GITHUB_SHA
        docker push nagerat/aspnetcoretest:$GITHUB_SHA
        docker push nagerat/aspnetcoretest:latest
        
